### ISSUE TITLE
A question on an Error message: Argument "num_descriptions". Incompatible with argument:  `max_target_seqs'

### ISSUE THREAD

**Issue by ilnamkang** [ndaniels/cablastp2#5]
I've been encountering an error message when I try using cablastx for metagenome analyses.

The error message is as follows:
Error: Argument "num_descriptions". Incompatible with argument:  `max_target_seqs'
  
My commands were as follows:
./bin/cablastp-compress --ext-seed-size 0 --match-seq-id-threshold 70 --ext-seq-id-threshold 60 --max-seeds 20 -p 40 catest viral_protein.faa
(viral_protein.faa is a protein fasta file used as a database.)

./bin/cablastp-xsearch catest query.fasta --blast-args -out test.txt -evalue 0.001 -seg no -query_gencode 11 -outfmt 6

(BLAST 2.2.28+ is installed in this Ubuntu server.)

I didn't use neither "num_descriptions" nor "max_target_seqs". 
How can I avoid the error message?

Thanks.

**Comment by ndaniels** [comment]
I will look into this, but later this evening. Apologies. It may be a documentation problem actually.

**Comment by ndaniels** [comment]
This should now be fixed on github; I apologize. You should be able to do a `go get -u github.com/ndaniels/cablastp2` to install the latest version.
